# Generated by Django 3.1.2 on 2020-12-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editcode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='text',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
